bench/compare.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/compare.hs
bench/compare: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/compare.hs \
  mk/toplibs
bench/match-list.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/match-list.hs
bench/match-list: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/match-list.hs \
  mk/toplibs
bench/match-noop.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/match-noop.hs
bench/match-noop: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/match-noop.hs \
  mk/toplibs
bench/match-triexpr.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/match-triexpr.hs
bench/match-triexpr: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/match-triexpr.hs \
  mk/toplibs
bench/pairs.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/pairs.hs
bench/pairs: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/pairs.hs \
  mk/toplibs
bench/sort.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/sort.hs
bench/sort: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/sort.hs \
  mk/toplibs
bench/tiers-complete.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/tiers-complete.hs
bench/tiers-complete: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/tiers-complete.hs \
  mk/toplibs
bench/tiers.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  bench/tiers.hs
bench/tiers: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/tiers.hs \
  mk/toplibs
eg/u-conjure: \
  eg/u-conjure.hs \
  mk/toplibs
eg/u-conjure.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  eg/u-conjure.hs
eg/u-extrapolate: \
  eg/u-extrapolate.hs \
  mk/toplibs
eg/u-extrapolate.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  eg/u-extrapolate.hs
eg/u-speculate: \
  eg/u-speculate.hs \
  mk/toplibs
eg/u-speculate.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  eg/u-speculate.hs
etc/hugs-backports/Data/Function.o: \
  etc/hugs-backports/Data/Function.hs
mk/All.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  mk/All.hs
mk/Toplibs.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs \
  mk/Toplibs.hs
src/Data/Express/Basic.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Basic.hs
src/Data/Express/Canon.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
src/Data/Express/Core.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Core.hs
src/Data/Express/Express/Derive.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs
src/Data/Express/Express.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Core.hs
src/Data/Express/Fixtures: \
  mk/toplibs
src/Data/Express/Fixtures.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
src/Data/Express/Fold.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Core.hs
src/Data/Express/Hole: \
  mk/toplibs
src/Data/Express/Hole.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Core.hs
src/Data/Express/Instances.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Basic.hs
src/Data/Express/Map.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Core.hs
src/Data/Express/Match.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Core.hs
src/Data/Express/Name/Derive.o: \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs
src/Data/Express/Name.o: \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Name.hs
src/Data/Express.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
src/Data/Express/Triexpr.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Core.hs
src/Data/Express/Utils/List.o: \
  src/Data/Express/Utils/List.hs
src/Data/Express/Utils.o: \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs
src/Data/Express/Utils/String.o: \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils/List.hs
src/Data/Express/Utils/TH.o: \
  src/Data/Express/Utils/TH.hs
src/Data/Express/Utils/Typeable.o: \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs
test/basic.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/basic.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/basic: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/basic.hs \
  mk/toplibs
test/canon.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/canon.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/canon: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/canon.hs \
  mk/toplibs
test/core.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/core.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/core: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/core.hs \
  mk/toplibs
test/express-derive.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express-derive.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/express-derive: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express-derive.hs \
  mk/toplibs
test/express.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/express: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express.hs \
  mk/toplibs
test/fixtures.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fixtures.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/fixtures: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fixtures.hs \
  mk/toplibs
test/fold.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fold.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/fold: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fold.hs \
  mk/toplibs
test/hole.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/hole.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/hole: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/hole.hs \
  mk/toplibs
test/instances.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/instances.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/instances: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/instances.hs \
  mk/toplibs
test/listable.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/listable.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/listable: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/listable.hs \
  mk/toplibs
test/main.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/main.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/main: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/main.hs \
  mk/toplibs
test/map.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/map.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/map: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/map.hs \
  mk/toplibs
test/match.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/match.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/match: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/match.hs \
  mk/toplibs
test/name-derive.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name-derive.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/name-derive: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name-derive.hs \
  mk/toplibs
test/name.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/name: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name.hs \
  mk/toplibs
test/ord.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/ord.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/ord: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/ord.hs \
  mk/toplibs
test/show.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/show.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/show: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/show.hs \
  mk/toplibs
test/Test/ListableExpr.o: \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/Test.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/Test: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  mk/toplibs
test/triexpr.o: \
  test/triexpr.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/triexpr: \
  test/triexpr.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  mk/toplibs
test/typecheck.o: \
  test/typecheck.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express/Triexpr.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Core.hs
test/typecheck: \
  test/typecheck.hs \
  mk/toplibs
test/utils.o: \
  test/utils.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Express/Utils/Typeable.hs \
  src/Data/Express/Utils/TH.hs \
  src/Data/Express/Utils/String.hs \
  src/Data/Express/Utils.hs \
  src/Data/Express/Utils/List.hs \
  src/Data/Express.hs \
  src/Data/Express/Name.hs \
  src/Data/Express/Name/Derive.hs \
  src/Data/Express/Match.hs \
  src/Data/Express/Map.hs \
  src/Data/Express/Instances.hs \
  src/Data/Express/Hole.hs \
  src/Data/Express/Fold.hs \
  src/Data/Express/Fixtures.hs \
  src/Data/Express/Express.hs \
  src/Data/Express/Express/Derive.hs \
  src/Data/Express/Core.hs \
  src/Data/Express/Canon.hs \
  src/Data/Express/Basic.hs
test/utils: \
  test/utils.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  mk/toplibs
