bench/compare.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  bench/compare.hs
bench/compare: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/compare.hs \
  mk/toplibs
bench/pairs.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  bench/pairs.hs
bench/pairs: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/pairs.hs \
  mk/toplibs
bench/tiers.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  bench/tiers.hs
bench/tiers: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  bench/tiers.hs \
  mk/toplibs
eg/u-extrapolate: \
  eg/u-extrapolate.hs \
  mk/toplibs
eg/u-extrapolate.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  eg/u-extrapolate.hs
mk/All.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  mk/All.hs
mk/Toplibs.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs \
  mk/Toplibs.hs
Setup.o: \
  Setup.hs
Setup: \
  Setup.hs \
  mk/toplibs
src/Data/Haexpress/Basic.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Canon: \
  mk/toplibs
src/Data/Haexpress/Canon.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Core.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Express/Derive.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Express.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Fixtures: \
  mk/toplibs
src/Data/Haexpress/Fixtures.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Fold.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Hole.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Instances.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Map.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Core.hs
src/Data/Haexpress/Match.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Name/Derive.o: \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs
src/Data/Haexpress/Name.o: \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Name.hs
src/Data/Haexpress.o: \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
src/Data/Haexpress/Utils/List.o: \
  src/Data/Haexpress/Utils/List.hs
src/Data/Haexpress/Utils/String.o: \
  src/Data/Haexpress/Utils/String.hs
src/Data/Haexpress/Utils/TH.o: \
  src/Data/Haexpress/Utils/TH.hs
src/Data/Haexpress/Utils/Typeable.o: \
  src/Data/Haexpress/Utils/Typeable.hs
test/canon.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/canon.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/canon: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/canon.hs \
  mk/toplibs
test/core.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/core.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/core: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/core.hs \
  mk/toplibs
test/express-derive.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express-derive.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/express-derive: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express-derive.hs \
  mk/toplibs
test/express.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/express: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/express.hs \
  mk/toplibs
test/fixtures.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fixtures.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/fixtures: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fixtures.hs \
  mk/toplibs
test/fold.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fold.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/fold: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/fold.hs \
  mk/toplibs
test/hole.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/hole.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/hole: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/hole.hs \
  mk/toplibs
test/instances.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/instances.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/instances: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/instances.hs \
  mk/toplibs
test/listable.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/listable.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/listable: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/listable.hs \
  mk/toplibs
test/main.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/main.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/main: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/main.hs \
  mk/toplibs
test/map.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/map.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/map: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/map.hs \
  mk/toplibs
test/match.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/match.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/match: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/match.hs \
  mk/toplibs
test/name-derive.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name-derive.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/name-derive: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name-derive.hs \
  mk/toplibs
test/name.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/name: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/name.hs \
  mk/toplibs
test/ord.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/ord.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/ord: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/ord.hs \
  mk/toplibs
test/show.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/show.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/show: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  test/show.hs \
  mk/toplibs
test/Test/ListableExpr.o: \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/Test.o: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/Test: \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  mk/toplibs
test/utils.o: \
  test/utils.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  src/Data/Haexpress/Utils/Typeable.hs \
  src/Data/Haexpress/Utils/TH.hs \
  src/Data/Haexpress/Utils/String.hs \
  src/Data/Haexpress/Utils/List.hs \
  src/Data/Haexpress.hs \
  src/Data/Haexpress/Name.hs \
  src/Data/Haexpress/Name/Derive.hs \
  src/Data/Haexpress/Match.hs \
  src/Data/Haexpress/Map.hs \
  src/Data/Haexpress/Instances.hs \
  src/Data/Haexpress/Hole.hs \
  src/Data/Haexpress/Fold.hs \
  src/Data/Haexpress/Fixtures.hs \
  src/Data/Haexpress/Express.hs \
  src/Data/Haexpress/Express/Derive.hs \
  src/Data/Haexpress/Core.hs \
  src/Data/Haexpress/Canon.hs \
  src/Data/Haexpress/Basic.hs
test/utils: \
  test/utils.hs \
  test/Test.hs \
  test/Test/ListableExpr.hs \
  mk/toplibs
